import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import SyntaxHighlighter from "react-syntax-highlighter";
import style from "react-syntax-highlighter/dist/cjs/styles/hljs/xcode";
import { useEffect, useState } from "react";

interface Question {
  question: JSX.Element;
  answer: JSX.Element;
}

const questions: Question[] = [
  {
    question: <p>Hello!</p>,
    answer: <p>Hi!</p>,
  },
  {
    question: <p>What is the type of 42?</p>,
    answer: (
      <p>
        That is easy! it is <code>number</code>
      </p>
    ),
  },
  {
    question: <p>Is it the only type?</p>,
    answer: (
      <p>
        Well, you could also use <code>number | null</code>, for example.
      </p>
    ),
  },
];

const Home: NextPage = () => {
  const [step, setStep] = useState(0);

  console.log({ step });

  useEffect(() => {
    function handler(e: KeyboardEvent) {
      switch (e.key) {
        case "ArrowRight":
          setStep((s) => s + 1);
          return;
        case "ArrowLeft":
          setStep((s) => Math.max(0, s - 1));
          return;
      }
    }
    document.addEventListener("keydown", handler);
    return () => {
      document.removeEventListener("keydown", handler);
    };
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>The Little Typescripter</h1>

        <br />
        <br />

        {questions
          .slice(0, (step / 2 || 0) + 1)
          .map(({ question, answer }, i) => {
            return (
              <Question
                key={i}
                question={question}
                showAnswer={step > i * 2}
                answer={answer}
              />
            );
          })}
      </main>
    </div>
  );
};

interface QuestionProps {
  question: JSX.Element;
  answer: JSX.Element;
  showAnswer: boolean;
}

function Question({ question, answer, showAnswer }: QuestionProps) {
  return (
    <div className="row">
      <div className="question">{question}</div>
      <div className="answer">{showAnswer && answer}</div>
      <style jsx>
        {`
          .row {
            display: flex;
            width: 100%;
            border-bottom: 1px solid #c5c5c5;
            min-height: 50px;
            padding-top: 10px;
            padding-bottom: 10px;
          }

          .question,
          .answer {
            width: 100%;
          }
        `}
      </style>
    </div>
  );
}

const TS: React.FC = ({ children }) => {
  return (
    <SyntaxHighlighter
      customStyle={{ display: "inline-block", padding: 0, fontSize: "16px" }}
      language="typescript"
      style={style}
    >
      {children}
    </SyntaxHighlighter>
  );
};

export default Home;
